name: static-sizeof
version: 0.0.1
category: Data
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2018 Shao Cheng
license: BSD3
github: TerrorJack/static-sizeof

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md

ghc-options: -Wall

dependencies:
  - base
  - ghc
  - ghc-paths
  - template-haskell

library:
  source-dirs: src
  other-modules:
    - Data.SizeOf.Internals
  other-extensions:
    - DataKinds
    - TemplateHaskell
    - TypeFamilies
